In [1]:
from __future__ import print_function
import numpy as np
from numpy import newaxis as na
import matplotlib.pyplot as plt
from IPython.display import display, HTML
import os
import sys
import numpy as np
import shap
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

import pandas as pd
import numpy as np
from itertools import permutations
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from lightgbm import LGBMClassifier
from nltk.stem import PorterStemmer
from sklearn.metrics import classification_report

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

from nltk.corpus import stopwords  
from nltk.tokenize import word_tokenize  
from nltk.tokenize.treebank import TreebankWordDetokenizer
import csv 
from sklearn.naive_bayes import MultinomialNB

from sklearn.linear_model import SGDClassifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.metrics import classification_report, accuracy_score

In [2]:
# Let's import and prep the datasets

train=pd.read_csv('not_clean_train_four.csv', sep=',', encoding='utf-8')
test=pd.read_csv('not_clean_test_four.csv', sep=',', encoding='utf-8')

train.info()
train.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4698 entries, 0 to 4697
Data columns (total 3 columns):
text      4698 non-null object
label     4698 non-null object
target    4698 non-null int64
dtypes: int64(1), object(2)
memory usage: 110.2+ KB

                                                text         label  target
0   শালা মাতারচুদ খানকির পোলা ফলো করার মানুষ পাইলিনা      Personal       0
1  আবে ছালে রানু মন্ডল তো মেন্টাল,  একজন পাগল এর ...      Personal       0
2  ভারতীয় আধিপত্যবাদের বিরুদ্ধে সোচ্চার হতে দেখা ...  Geopolitical       3
3       ফেমিলি সো শালার তোর ভিডিওর শুরুতে আহ সাউন্ড।      Personal       0
4  স্কুল ছুটির পর গেট দিয়ে বের হওয়ার সময পিছন থেক...      Personal       0

In [3]:
test.info()
test.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
text      1000 non-null object
label     1000 non-null object
target    1000 non-null int64
dtypes: int64(1), object(2)
memory usage: 23.5+ KB

                                                text         label  target
0  বৌদির দুধ দেকে তো আমার ই চোখ ঠিক ছিলো না - পোল...      Personal       0
1  এই সরকার কে যারা নির্লজ্জের মত সাপোর্ট দিয়েছে ...     Political       1
2  পিলখানা হত্যাকান্ড বাংলাদেশের প্রতিরক্ষা ব্যবস...  Geopolitical       3
3  ভারতের অর্থনীতি নিয়ে আপনাদের ভাবতে হবে না। ভা...  Geopolitical       3
4            খানকির পুলা মালায়নদের মেরে সাফা করে ফেল      Personal       0

In [4]:
stop_words='stopwords-bn.txt'
text_data=[]

with open(stop_words,'r',encoding='utf-8') as temp_output_file:
    reader=csv.reader(temp_output_file, delimiter='\n')
    for row in reader:
        text_data.append(row)
stop_word_list=[x[0] for x in text_data]

In [5]:
stop_words = set(stop_word_list)  

def textCleaner(example_sent): 
    word_tokens = word_tokenize(example_sent)  
    #filtered_sentence = [w for w in word_tokens if not w in stop_words]
    filtered_train = TreebankWordDetokenizer().detokenize(word_tokens)

    return filtered_train

In [6]:
filtered_test = test['text'].apply(textCleaner)

In [7]:
filtered_train = train['text'].apply(textCleaner)

In [8]:
train['label'].value_counts()

Personal        1798
Geopolitical    1457
Religious        784
Political        659
Name: label, dtype: int64

In [9]:
train['target'].value_counts()

0    1798
3    1457
2     784
1     659
Name: target, dtype: int64

In [10]:
x_train, y_train = filtered_train, train['target'].values
x_test, y_test = filtered_test, test['target'].values

In [11]:
#Initialize the `tfidf_vectorizer` 

tfidf_vectorizer = CountVectorizer()
#Fit and transform the training data 
x_train = tfidf_vectorizer.fit_transform(x_train)
#Transform the test set 
x_test = tfidf_vectorizer.transform(x_test)

In [12]:
tfidf_vectorizer.vocabulary_

{'রচ': 1791,
 'নক': 1275,
 'ফল': 1445,
 'কর': 714,
 'ইল': 325,
 'আব': 198,
 'মন': 1652,
 'ডল': 1089,
 'একজন': 477,
 'গল': 848,
 'এর': 551,
 'আচরণ': 150,
 'এমন': 542,
 'হওয়': 2147,
 'কথ': 683,
 'অব': 65,
 'আছ': 152,
 'রত': 1810,
 'আধ': 172,
 'পত': 1368,
 'যব': 1744,
 'হত': 2160,
 'রক': 1776,
 'আসল': 243,
 'লপ': 1925,
 'ওর': 614,
 'আহ': 245,
 'উন': 385,
 'পর': 1390,
 'সময': 2093,
 'ছন': 938,
 'বল': 1542,
 'রদ': 1822,
 'আয়': 253,
 'কত': 673,
 'খর': 785,
 'এখ': 504,
 'এস': 564,
 'গর': 842,
 'সন': 2058,
 'করত': 720,
 'এই': 446,
 'আম': 204,
 'সল': 2111,
 'নদ': 1298,
 'জন': 983,
 'সমব': 2090,
 'দন': 1191,
 'আচ': 148,
 'রশ': 1871,
 'করছ': 717,
 'উপর': 402,
 'অত': 30,
 'রই': 1770,
 'অর': 90,
 'আওয়': 134,
 'হল': 2182,
 'নড়': 1342,
 'আমর': 208,
 'এন': 532,
 'সকল': 2037,
 'অভ': 81,
 'আন': 174,
 'এখন': 506,
 'এট': 515,
 'য়দ': 2230,
 'ইন': 299,
 'আর': 212,
 'কয়': 750,
 'কট': 668,
 'এব': 538,
 'এগ': 510,
 'এরপর': 556,
 'ধর': 1251,
 'আযহ': 211,
 'ইত': 294,
 'কখন': 656,
 'চল': 916,
 'গত': 819,
 'এক': 470,
 'লড': 1920,
 'ফর': 1441,
 'মত': 1642,
 'মদ': 1647,
 'মল': 1682,
 'পছন': 1359,
 'রর': 1867,
 'মধ': 1651,
 'আরব': 220,
 'দশ': 1218,
 'বছর': 1492,
 'এসএফ': 566,
 'শত': 1962,
 'করল': 725,
 'হচ': 2150,
 'এদ': 528,
 'নজর': 1287,
 'তথ': 1124,
 'নবত': 1311,
 'আঙ': 147,
 'গণধর': 815,
 'ষণ': 2005,
 'আনন': 177,
 'ওয়': 627,
 'দক': 1177,
 'অঙ': 24,
 'আপত': 185,
 'হয়': 2192,
 'উঠ': 370,
 'ওই': 589,
 'রণ': 1804,
 'উঠল': 375,
 'বক': 1468,
 'সমস': 2095,
 '৮০': 2301,
 'পস': 1413,
 'আধম': 173,
 'অপ': 53,
 'টক': 1036,
 'সব': 2067,
 'ইসল': 338,
 'সম': 2082,
 'অথচ': 38,
 'রয়': 1895,
 'মমত': 1667,
 'হয়ন': 2198,
 'সফ': 2063,
 'হউক': 2142,
 'আপন': 187,
 'আশ': 233,
 'অন': 45,
 'সলম': 2112,
 'জল': 1006,
 'মর': 1671,
 'এখনও': 508,
 'ঈম': 346,
 'এত': 519,
 'আবছ': 199,
 'ঘটন': 865,
 'খবর': 779,
 'গজ': 801,
 'য়গ': 2223,
 'মসজ': 1687,
 'বর': 1531,
 'কম': 704,
 'ইক': 269,
 'ওন': 605,
 'ওত': 603,
 'আজ': 154,
 'ইশ': 328,
 'বড়': 1570,
 'সক': 2035,
 'তর': 1140,
 'দত': 1188,
 'মজ': 1632,
 'গব': 833,
 'জখ': 959,
 'ইব': 314,
 'লগ': 1910,
 'একই': 471,
 'বব': 1525,
 'ষড়যন': 2022,
 'একট': 479,
 'বই': 1450,
 'তঘ': 1115,
 'যখন': 1715,
 'পন': 1381,
 'অবস': 76,
 'তখন': 1110,
 'একরকম': 495,
 'হব': 2171,
 'অস': 99,
 'আত': 167,
 'মপ': 1662,
 'রপ': 1839,
 'ফন': 1439,
 'বলব': 1551,
 'বন': 1515,
 'খব': 778,
 'ফক': 1429,
 'ইর': 323,
 'ডম': 1087,
 'রন': 1832,
 'মড়': 1700,
 'করব': 723,
 'পয়দ': 1425,
 'যত': 1724,
 'খছ': 767,
 'লখ': 1909,
 'আল': 224,
 'যদ': 1734,
 'ওদ': 604,
 'বয়ফ': 1581,
 'ডক': 1079,
 'কব': 696,
 'ডগ': 1082,
 'ডলক': 1090,
 'বলছ': 1545,
 'লজ': 1915,
 'উচ': 357,
 'ওইয': 592,
 'খল': 787,
 'নয়ন': 1345,
 'লছ': 1914,
 'লত': 1921,
 'মকরছ': 1622,
 'দরক': 1201,
 'অশ': 97,
 'উল': 417,
 'আসছ': 238,
 'ইম': 317,
 'জঙ': 971,
 'আখ': 140,
 'সঙ': 2040,
 'তদ': 1125,
 'বলত': 1547,
 'ঝল': 1026,
 'রভ': 1855,
 'বনধ': 1519,
 'নর': 1323,
 'রজ': 1796,
 'অফ': 64,
 'বলল': 1553,
 'ধরল': 1258,
 'ওক': 594,
 'কবর': 699,
 'সময়': 2097,
 'হইছ': 2135,
 'রট': 1802,
 'নয': 1322,
 'ধরন': 1255,
 'ওয': 613,
 'তদন': 1126,
 'চলব': 920,
 'সবচ': 2072,
 'টতম': 1046,
 'জড়': 1016,
 'ধন': 1237,
 'যক': 1709,
 'সহ': 2119,
 'করন': 722,
 'সত': 2050,
 'নঢব': 1293,
 'উদ': 382,
 'শরম': 1985,
 'অলআউট': 94,
 'সৎ': 2128,
 'রইল': 1772,
 'নম': 1315,
 'পথ': 1371,
 'হস': 2189,
 'কল': 728,
 'রল': 1870,
 'রব': 1849,
 'উপয': 401,
 'জব': 1002,
 'বদল': 1512,
 'একশট': 499,
 'তল': 1149,
 'দর': 1200,
 'শয়ত': 1992,
 'বজ': 1494,
 'চলত': 919,
 'ষম': 2016,
 'নয়': 1343,
 'নত': 1294,
 'শল': 1986,
 'গন': 826,
 'আপনজন': 188,
 'পরছ': 1394,
 'বস': 1558,
 'বকধ': 1474,
 'য়র': 2239,
 'দল': 1212,
 'লর': 1936,
 'ইনক': 300,
 'উপক': 395,
 'একদ': 483,
 'টফ': 1053,
 'সদর': 2055,
 '২০২০': 2272,
 'দখল': 1180,
 'আই': 111,
 'উড': 376,
 'উর': 415,
 'কদ': 684,
 'জত': 978,
 'য়ন': 2231,
 'চলছ': 918,
 'অথব': 39,
 'ঘর': 877,
 'শখ': 1953,
 'হয': 2175,
 'গক': 797,
 'জনগণ': 987,
 'কন': 686,
 'অপর': 59,
 'পরক': 1393,
 'সকলক': 2038,
 'মরত': 1676,
 'বত': 1503,
 'অমর': 86,
 'বড়ল': 1576,
 'রস': 1875,
 'পদ': 1374,
 'ৎস': 2205,
 'ইনশন': 308,
 'ইজ': 283,
 'জনপ': 993,
 'মনট': 1655,
 'হরন': 2180,
 'একব': 490,
 'হর': 2177,
 'ময়দ': 1702,
 'গভ': 837,
 'হঠ': 2159,
 'ময়': 1701,
 'ঐদ': 579,
 'আস': 237,
 'ঝখ': 1019,
 'এল': 561,
 'মহ': 1692,
 'রম': 1857,
 'একত': 480,
 'চন': 905,
 'হয়য': 2200,
 'দয়': 1227,
 'দগদগ': 1183,
 'ষত': 2009,
 'ঝব': 1024,
 'ইপ': 311,
 'পড়': 1417,
 'উজফ': 366,
 'হয়ত': 2197,
 'রণগত': 1805,
 'চয়ই': 931,
 'এতট': 524,
 'লক': 1905,
 'ষয়': 2023,
 'বয়স': 1582,
 'উভয়': 411,
 'পরম': 1400,
 'তব': 1134,
 'রপর': 1843,
 'শপ': 1972,
 'শব': 1975,
 'ভয': 1597,
 'এরকম': 553,
 'যতদ': 1728,
 'ষন': 2011,
 'তত': 1121,
 'তম': 1138,
 'বড': 1502,
 'ওব': 609,
 'উগ': 355,
 'জয়': 1017,
 'টন': 1049,
 'এজন': 514,
 'পক': 1351,
 'সওয়': 2034,
 'আগ': 142,
 '২৫': 2277,
 'হজরত': 2155,
 'ওরশ': 620,
 'লন': 1923,
 'উনদ': 391,
 'পচ': 1356,
 'ইকব': 270,
 'বহ': 1564,
 'ষমত': 2017,
 'সহকর': 2121,
 'ইহ': 339,
 'পণ': 1367,
 'যম': 1750,
 'শর': 1981,
 'ছব': 940,
 'শন': 1970,
 'চট': 901,
 'সরক': 2102,
 'বদ': 1507,
 'রফত': 1847,
 'যট': 1719,
 'মড': 1639,
 'আচড': 149,
 'মরল': 1681,
 'ওগ': 596,
 'নল': 1330,
 'ফখর': 1432,
 'সর': 2101,
 'বয়': 1577,
 'আওয': 132,
 'জলস': 1011,
 'যন': 1739,
 'অসহ': 106,
 'য়ত': 2229,
 'যবহ': 1748,
 'জনক': 985,
 'যবস': 1747,
 'ইগ': 273,
 'চক': 893,
 'রচন': 1792,
 'বহন': 1565,
 'মচ': 1630,
 'রতবর': 1817,
 'আগমন': 144,
 'রণত': 1807,
 'ঘট': 862,
 'আরও': 216,
 'নগণ': 1280,
 'ঠনক': 1069,
 'আক': 136,
 'রমণ': 1858,
 'অম': 83,
 'ইস': 332,
 'এরস': 560,
 'অনল': 51,
 'পরব': 1398,
 'রহম': 1890,
 '২বছর': 2267,
 'খত': 770,
 'আয': 210,
 'এজ': 513,
 'যখণ': 1714,
 'আলম': 227,
 'ইড': 293,
 'কনডম': 690,
 'বইত': 1453,
 'কয়ল': 757,
 'ময়ল': 1703,
 'সভ': 2081,
 'ভয়ত': 1609,
 'রধ': 1829,
 'অবসর': 78,
 'দম': 1196,
 'টফর': 1054,
 'সবসময়': 2080,
 'মই': 1611,
 'ভয়': 1606,
 'উপরও': 403,
 'পড়ছ': 1418,
 'ছয়': 949,
 'ইদ': 297,
 'ষট': 2004,
 'চয': 911,
 'ৎক': 2202,
 'শহ': 1989,
 'কখনও': 658,
 'একম': 492,
 'শট': 1959,
 'ইদহ': 298,
 'এফ': 537,
 'য়ক': 2218,
 'দব': 1194,
 'বঙ': 1484,
 'গবন': 834,
 'নস': 1335,
 'মগ': 1624,
 'জস': 1014,
 'ইছ': 280,
 'করচ': 716,
 'গলর': 854,
 'পল': 1406,
 'লঘ': 1911,
 'হইল': 2139,
 'ধভ': 1245,
 'থপর': 1168,
 'ইচ': 276,
 'ছস': 946,
 'রছ': 1794,
 'নব': 1310,
 'আয়শ': 256,
 'উম': 413,
 'এইব': 460,
 'যতসব': 1732,
 'উপস': 405,
 '72': 8,
 'ইউন': 263,
 'এমনক': 544,
 'রও': 1775,
 'রনগ': 1833,
 'আজক': 157,
 'পড়ল': 1422,
 'ইউস': 265,
 'ফজ': 1433,
 'নফ': 1309,
 'ভর': 1598,
 'উত': 377,
 'ধইর': 1228,
 '২ট': 2266,
 'ইখ': 272,
 'কবছর': 697,
 'পরই': 1391,
 'চচ': 897,
 'বলচ': 1544,
 'নচ': 1283,
 'মদখ': 1648,
 'গলদ': 852,
 'কজন': 665,
 'ইয়': 341,
 '৭ত': 2295,
 'চশ': 923,
 'গনহত': 831,
 'রহস': 1893,
 'ওপর': 608,
 'রহ': 1884,
 'যদন': 1735,
 'যকর': 1711,
 'নষ': 1334,
 'বউয়': 1466,
 'সপ': 2061,
 'বকছ': 1470,
 'উজ': 361,
 'হক': 2148,
 'লব': 1930,
 'এনপ': 535,
 'অগ': 21,
 'ইনশ': 307,
 'রথ': 1820,
 'ষদ': 2010,
 'শদ': 1967,
 'আজব': 159,
 'শক': 1951,
 'ইছস': 282,
 'একমত': 493,
 'জলদ': 1008,
 'গদ': 824,
 'রতক': 1813,
 'উপহ': 406,
 'bong': 10,
 'ইনচ': 301,
 'এমপ': 547,
 'গলও': 849,
 'ভগব': 1586,
 'অক': 18,
 'তজ': 1118,
 'ঞক': 1028,
 'যতট': 1727,
 'অতট': 35,
 'ওরজ': 617,
 'সস': 2116,
 'কইর': 643,
 'কস': 744,
 'টপ': 1050,
 'পড': 1366,
 'ওইদ': 591,
 'আপ': 183,
 'হনএখন': 2168,
 'দয': 1199,
 'অইড': 16,
 'নওয': 1272,
 'ময': 1670,
 'রগঠন': 1787,
 'টস': 1063,
 'উলঙ': 418,
 'রণট': 1806,
 'ইট': 291,
 'উনট': 389,
 'ফত': 1437,
 'লস': 1940,
 'কই': 636,
 'ষক': 1995,
 'টত': 1045,
 'আসস': 244,
 'সমপরক': 2089,
 'নন': 1305,
 'পশ': 1408,
 'অধ': 42,
 'আদ': 170,
 'টল': 1062,
 'ভক': 1585,
 'যশ': 1756,
 'জর': 1005,
 'জঘন': 970,
 'নমন': 1318,
 'টব': 1056,
 'লউন': 1902,
 'সট': 2046,
 'হছ': 2151,
 'রয': 1865,
 'ষকদ': 1996,
 'শরণ': 1982,
 'ইউএনএইচস': 260,
 'কয': 713,
 'কশ': 739,
 'আওম': 131,
 'থমন': 1171,
 'রমন': 1860,
 'জই': 950,
 'আইড': 117,
 'মক': 1619,
 'চয়': 930,
 'এসব': 568,
 'ঝত': 1023,
 'থন': 1166,
 'বসল': 1563,
 'বদর': 1511,
 'হইয়': 2141,
 'দছ': 1184,
 'পড়ত': 1420,
 'একস': 501,
 'ডকটর': 1080,
 'আসন': 240,
 'বজন': 1496,
 'রকম': 1778,
 'অজ': 26,
 'কহ': 748,
 'হইত': 2136,
 'টট': 1043,
 'টর': 1060,
 'গণ': 811,
 'যর': 1754,
 'কলমধ': 736,
 'সদ': 2054,
 'হয়র': 2201,
 'গনপ': 830,
 'ছত': 935,
 'খলন': 788,
 'যথ': 1733,
 'কওয়': 651,
 'কনর': 692,
 'কইত': 639,
 'এইসব': 465,
 'লল': 1937,
 'ঔই': 628,
 'ছট': 933,
 'পয়স': 1426,
 'হয়ছ': 2196,
 'অবশত': 75,
 'আসব': 241,
 'এইদ': 458,
 'অসৎ': 107,
 'চর': 912,
 'পব': 1384,
 'রআন': 1769,
 'কষ': 741,
 'সইত': 2027,
 'ইসব': 336,
 'দরদ': 1205,
 'তন': 1127,
 'গণহত': 818,
 'য়খ': 2221,
 'নট': 1290,
 'শরন': 1984,
 'উজএর': 363,
 'রড': 1803,
 'ভবত': 1595,
 'বলদ': 1548,
 'নওয়': 1274,
 'ইফ': 312,
 'ষণক': 2006,
 '100': 1,
 '120': 3,
 'এইগ': 451,
 'তরণ': 1143,
 'ধক': 1229,
 'পরবর': 1399,
 'পদক': 1375,
 'পতন': 1370,
 'ঠষ': 1074,
 'ঐট': 577,
 'লম': 1934,
 'আজমক': 160,
 'দরল': 1210,
 'কতক': 676,
 'তয়': 1158,
 'পগন': 1354,
 'ঐই': 574,
 'মস': 1685,
 'ডয়': 1093,
 'বম': 1528,
 'উনর': 393,
 'লউনদ': 1903,
 'পদগ': 1376,
 'এমনট': 545,
 'একফ': 489,
 'থর': 1172,
 'আটক': 164,
 'জতন': 979,
 '৩শ': 2280,
 'উক': 353,
 'আলমক': 228,
 'জক': 955,
 'ধরব': 1256,
 'আজহ': 161,
 'খখ': 764,
 'ততদ': 1122,
 '১৩': 2251,
 'মণ': 1640,
 'অমন': 84,
 'লয়': 1945,
 'এইখ': 450,
 'এইভ': 461,
 'অনন': 50,
 'আনর': 180,
 'রগ': 1785,
 'শও': 1950,
 'আরম': 222,
 'একদম': 484,
 'ইজজত': 284,
 '২য': 2268,
 '৭২': 2298,
 'দহয়': 1225,
 'উপমহ': 400,
 'অহ': 108,
 'হই': 2134,
 'নজ': 1285,
 'ডউইথ': 1077,
 'আজগভ': 158,
 'আমল': 209,
 'ভন': 1591,
 'ভব': 1593,
 'জনগ': 986,
 'অবশ': 74,
 'যই': 1704,
 'রনগর': 1834,
 'ববর': 1526,
 'গতক': 820,
 'কতট': 678,
 'ঘন': 874,
 'গতর': 822,
 'লও': 1904,
 'টয়': 1065,
 'রনট': 1835,
 'দড়': 1226,
 'মরছ': 1674,
 'খরচ': 786,
 'পয': 1387,
 'ওখ': 595,
 'উৎসব': 433,
 'নঝ': 1289,
 'নরস': 1329,
 'হইব': 2137,
 'লদ': 1922,
 'কড়': 749,
 'এইট': 455,
 'সয়ত': 2132,
 'কঠ': 670,
 'রহমত': 1891,
 'কতদ': 679,
 'উপলক': 404,
 'লকথ': 1907,
 'মনক': 1653,
 'আনত': 176,
 'ঘদ': 872,
 'ইয': 322,
 'শধ': 1968,
 'পথভ': 1372,
 'রষ': 1874,
 'য়ণগঞ': 2227,
 'ওল': 621,
 'সমর': 2094,
 'হন': 2167,
 'সমন': 2088,
 'ঞত': 1029,
 'ঊক': 440,
 'পদত': 1378,
 'জনগন': 989,
 'দলই': 1213,
 'সলমনদ': 2113,
 'হছছ': 2152,
 'ধরসন': 1260,
 'সচ': 2042,
 'সবসম': 2078,
 'আইন': 120,
 'অবনত': 70,
 'ঝছ': 1022,
 'ঘনবসত': 875,
 'টকর': 1037,
 'যও': 1707,
 'গস': 856,
 'গঠন': 808,
 'ইঙ': 275,
 'আভ': 203,
 'যতব': 1730,
 'কচ': 661,
 'চপ': 906,
 'রকর': 1780,
 'গরম': 847,
 'ছপ': 939,
 'উজপ': 365,
 'আরত': 219,
 'ঝড়': 1027,
 'বড়ই': 1571,
 'বলন': 1550,
 'মসউদ': 1686,
 'আঘ': 146,
 'দমন': 1198,
 'টকশ': 1038,
 'কপট': 695,
 'এতই': 520,
 'পষ': 1412,
 'যণ': 1723,
 'মকর': 1621,
 'এডম': 518,
 'কইল': 644,
 'বশ': 1556,
 'জশ': 1012,
 '১৪': 2253,
 'নগ': 1279,
 'একসময়': 503,
 'জম': 1003,
 'পট': 1363,
 'অল': 93,
 'চআই': 890,
 'সয': 2100,
 'উভয': 410,
 'আইএসক': 113,
 'ছলছ': 944,
 'পযন': 1388,
 'মতন': 1643,
 'ভয়ঙ': 1608,
 'ণম': 1098,
 'বউ': 1459,
 'পযর': 1389,
 'কলক': 729,
 'সরম': 2109,
 'বসত': 1560,
 'চরম': 915,
 'আরএকট': 214,
 'জকর': 958,
 'ওঝ': 599,
 'এভ': 540,
 'নজম': 1286,
 'খজনক': 768,
 'হতভ': 2165,
 'খন': 773,
 'শই': 1947,
 'রইছ': 1771,
 '১১': 2249,
 'জতব': 980,
 'সহক': 2120,
 'ষয়ট': 2025,
 'রঞ': 1801,
 'নশন': 1332,
 'কয়ট': 753,
 'এনজ': 534,
 'নইল': 1267,
 'বরই': 1532,
 'ধরষন': 1259,
 'উনম': 392,
 'আবর': 201,
 'আহম': 248,
 'শফ': 1974,
 'মছ': 1631,
 'দরচ': 1202,
 'ভড়': 1605,
 'ড়ত': 2207,
 'রফর': 1848,
 'পশন': 1409,
 'সজ': 2044,
 '১০': 2245,
 '২০': 2269,
 'রহণ': 1885,
 'লট': 1917,
 'বইন': 1454,
 'লবন': 1932,
 'ধরক': 1252,
 'হওন': 2145,
 'মরব': 1680,
 'চড়': 928,
 'পশমও': 1411,
 'উচত': 359,
 'আদর': 171,
 'অপরক': 60,
 'ধমক': 1247,
 'দশব': 1221,
 'রসম': 1881,
 'হতন': 2163,
 'অরজ': 92,
 'রশত': 1872,
 'ভরস': 1603,
 'সফর': 2065,
 'এহল': 571,
 'ঠন': 1068,
 'সবসময': 2079,
 'অবহ': 79,
 'সছ': 2043,
 'এরই': 552,
 'ড়ছ': 2206,
 'কমত': 707,
 'সৎম': 2130,
 'অচল': 25,
 'রধদ': 1830,
 'নপ': 1307,
 'আড': 166,
 'ইমস': 321,
 'লফ': 1928,
 'য়ম': 2237,
 'রজন': 1799,
 'ধম': 1246,
 'ষস': 2021,
 'চব': 907,
 'রদর': 1826,
 'রথম': 1821,
 'অবদ': 69,
 'ধধ': 1236,
 'মকহ': 1623,
 'ঈস': 348,
 'আসত': 239,
 'উপ': 394,
 'বউড': 1461,
 'ড়ল': 2213,
 'রখ': 1782,
 'উয়র': 439,
 'দগ': 1182,
 '১৯৭৪': 2265,
 'রফ': 1846,
 'ধদ': 1235,
 'যয়ও': 1765,
 'এককথ': 472,
 'কবরস': 700,
 'পঞ': 1362,
 'একশ': 498,
 'করস': 727,
 'আইস': 125,
 'তরক': 1141,
 'এইসসব': 466,
 'ধরম': 1257,
 'আট': 163,
 'বরন': 1539,
 'মকব': 1620,
 'বভ': 1527,
 'এরকমই': 554,
 'সমই': 2083,
 'উয়': 438,
 'আইত': 119,
 'দরন': 1206,
 'জকম': 957,
 'আউট': 126,
 'হওয': 2146,
 'ভদ': 1589,
 'গড়গড়': 858,
 'এড': 516,
 'একসময': 502,
 'রমভ': 1863,
 'ডদ': 1084,
 'করক': 715,
 'বরতম': 1538,
 'ইউ': 259,
 'করদ': 721,
 'ঘড়': 883,
 'করশ': 726,
 'বরসত': 1541,
 'আফ': 194,
 'টইট': 1032,
 'অসভ': 104,
 'শতকর': 1964,
 '85': 9,
 'ষর': 2019,
 'যমত': 1751,
 'কজনক': 666,
 'টয': 1059,
 'যস': 1757,
 'উড়': 435,
 'ঘটছ': 863,
 'অপম': 58,
 'ঈশ': 347,
 'বরও': 1533,
 'টয়ল': 1066,
 'তড়': 1157,
 'মৎস': 1699,
 'পদমন': 1379,
 'উপজ': 396,
 'উশক': 421,
 'ফইন': 1428,
 'বসব': 1562,
 'গঠ': 807,
 'কক': 652,
 '৬৫': 2294,
 'ফট': 1436,
 'ওসহ': 625,
 'ঠর': 1072,
 'কতভ': 682,
 'জনগণক': 988,
 '৭১': 2297,
 '৯২': 2303,
 'সমভব': 2091,
 'বয়কট': 1579,
 'ইগন': 274,
 'বধ': 1514,
 'রতই': 1811,
 'মনন': 1660,
 'আফগ': 195,
 'উইক': 351,
 'উছ': 360,
 'দরত': 1204,
 'নহ': 1340,
 'চমৎক': 910,
 'সবধর': 2076,
 'থক': 1159,
 'একশত': 500,
 'উলট': 419,
 'ওআর': 587,
 'গগ': 798,
 'উআর': 349,
 'সদস': 2056,
 'লঙ': 1912,
 'মব': 1663,
 'করম': 724,
 'ক৷': 759,
 ...}

# Naive Bayes

In [12]:
# Let's run the model and get its accuracy score

nb = MultinomialNB(alpha = 0.1)
nb.fit(x_train, y_train)
y_pred = nb.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

from sklearn.metrics import matthews_corrcoef
print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.70      0.75      0.72       391
Geopolitical       0.59      0.37      0.45       155
   Religious       0.64      0.56      0.60       173
   Political       0.61      0.73      0.67       281

    accuracy                           0.65      1000
   macro avg       0.64      0.60      0.61      1000
weighted avg       0.65      0.65      0.64      1000

MCC: 0.5069699279225371

# KNN

In [18]:
# Let's run the model and get its accuracy score

knn = KNeighborsClassifier(n_neighbors=12)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

#from sklearn.metrics import matthews_corrcoef
print('MCC:', matthews_corrcoef(y_test, y_pred))

NB: 
    MCC: 0.5069699279225371
    P: 0.65
    R: 0.65
    F1: 0.64
KNN: 
    MCC: 0.38146812800251834
    P: 0.6
    R: 0.56
    f1: 0.5
        
SVM: 
    MCC: 0.5327963238498397
    P: 0.67
    R: 0.67
    F1: 0.66
LR: 
    MCC: 0.5417725759571228
    P: 0.68
    R: 0.68
    F1: 0.67
RF: 
    MCC: 0.5599981362428225
    P: 0.69
    R: 0.69
    f1: 0.68
        
GBT: 
    MCC: 0.56801039026076
    P: 0.71
    R: 0.69
    f1: 0.68

              precision    recall  f1-score   support

    Personal       0.49      0.95      0.65       391
Geopolitical       0.38      0.03      0.06       155
   Religious       0.67      0.19      0.30       173
   Political       0.82      0.54      0.65       281

    accuracy                           0.56      1000
   macro avg       0.59      0.43      0.41      1000
weighted avg       0.60      0.56      0.50      1000

MCC: 0.38146812800251834

# SVM

In [19]:
# Let's run the model and get its accuracy score
from sklearn.svm import SVC
svm=SVC(kernel="linear", degree=5, probability=True) # 0.9306853582554517

svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.65      0.87      0.74       391
Geopolitical       0.57      0.33      0.42       155
   Religious       0.70      0.54      0.61       173
   Political       0.74      0.67      0.71       281

    accuracy                           0.67      1000
   macro avg       0.67      0.60      0.62      1000
weighted avg       0.67      0.67      0.66      1000

MCC: 0.5327963238498397

# Gaussian NB

In [21]:
gnb = GaussianNB()
gnb.fit(x_train.toarray(), y_train)

y_pred = gnb.predict(x_test.toarray())

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.50      0.15      0.23       391
Geopolitical       0.23      0.71      0.35       155
   Religious       0.28      0.51      0.36       173
   Political       0.47      0.17      0.25       281

    accuracy                           0.30      1000
   macro avg       0.37      0.38      0.30      1000
weighted avg       0.41      0.30      0.28      1000

MCC: 0.14996247487606365

# LR

In [22]:
# Let's run the model and get its accuracy score

lr = LogisticRegression()
lr.fit(x_train, y_train)

y_pred = lr.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.66      0.84      0.74       391
Geopolitical       0.61      0.41      0.49       155
   Religious       0.67      0.55      0.60       173
   Political       0.75      0.68      0.72       281

    accuracy                           0.68      1000
   macro avg       0.67      0.62      0.64      1000
weighted avg       0.68      0.68      0.67      1000

MCC: 0.5417725759571228

# Decision Tree Classifier

In [23]:
dt = DecisionTreeClassifier()

dt.fit(x_train, y_train)
y_pred = dt.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.67      0.66      0.67       391
Geopolitical       0.43      0.41      0.42       155
   Religious       0.49      0.55      0.52       173
   Political       0.69      0.68      0.68       281

    accuracy                           0.61      1000
   macro avg       0.57      0.57      0.57      1000
weighted avg       0.61      0.61      0.61      1000

MCC: 0.45026874887830265

# Random Forest

In [24]:
# Let's run the model and get its accuracy score

rf = RandomForestClassifier()
rf.fit(x_train, y_train)
y_pred = rf.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.68      0.84      0.75       391
Geopolitical       0.65      0.34      0.45       155
   Religious       0.69      0.60      0.64       173
   Political       0.73      0.73      0.73       281

    accuracy                           0.69      1000
   macro avg       0.69      0.63      0.64      1000
weighted avg       0.69      0.69      0.68      1000

MCC: 0.5599981362428225

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from lightgbm import LGBMClassifier
from nltk.stem import PorterStemmer
from sklearn.metrics import classification_report

# Gradient Boosted Trees

In [25]:
# Let's run the model and get its accuracy score

gbt = GradientBoostingClassifier(random_state=0, n_estimators=200)
gbt.fit(x_train, y_train)
y_pred = gbt.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.63      0.90      0.74       391
Geopolitical       0.72      0.35      0.47       155
   Religious       0.74      0.57      0.64       173
   Political       0.81      0.68      0.74       281

    accuracy                           0.69      1000
   macro avg       0.72      0.62      0.65      1000
weighted avg       0.71      0.69      0.68      1000

MCC: 0.56801039026076

In [90]:
test.target.unique()

array([0, 1, 3, 2])

In [123]:
import eli5
eli5.show_weights(gbt, vec=tfidf_vectorizer, top=15, target_names = test.target.unique())

# AdaBoostClassifier

In [21]:
# Let's run the model and get its accuracy score

ab = AdaBoostClassifier(random_state=0, n_estimators=200)
ab.fit(x_train, y_train)
y_pred = ab.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

print('MCC:', matthews_corrcoef(y_test, y_pred))

              precision    recall  f1-score   support

    Personal       0.66      0.88      0.75       391
Geopolitical       0.58      0.39      0.47       155
   Religious       0.64      0.54      0.59       173
   Political       0.80      0.66      0.72       281

    accuracy                           0.68      1000
   macro avg       0.67      0.62      0.63      1000
weighted avg       0.68      0.68      0.67      1000

# LGBMClassifier

In [ ]:
# Let's run the model and get its accuracy score

LGBM = LGBMClassifier(random_state=0, n_estimators=200)
LGBM.fit(x_train, y_train)
y_pred = LGBM.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

# PassiveAggressiveClassifier

In [52]:
from sklearn.linear_model import PassiveAggressiveClassifier

PAC = PassiveAggressiveClassifier(max_iter=10000, random_state=0, tol=1e-5)

PAC.fit(x_train, y_train)
y_pred = PAC.predict(x_test)

categories = ['Personal', 'Geopolitical','Religious','Political']
print(classification_report(y_test, y_pred, target_names=categories))

              precision    recall  f1-score   support

    Personal       0.66      0.74      0.70       391
Geopolitical       0.58      0.40      0.47       155
   Religious       0.64      0.55      0.59       173
   Political       0.66      0.71      0.68       281

    accuracy                           0.65      1000
   macro avg       0.63      0.60      0.61      1000
weighted avg       0.64      0.65      0.64      1000

In [54]:
from sklearn.feature_selection import SelectFromModel

import matplotlib.pyplot as plt
import numpy as np

from sklearn.datasets import load_diabetes
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LassoCV

diabetes = load_diabetes()

X = diabetes.data
y = diabetes.target

In [55]:
feature_names = diabetes.feature_names
print(feature_names)

clf = LassoCV().fit(X, y)
importance = np.abs(clf.coef_)
print(importance)

idx_third = importance.argsort()[-3]
threshold = importance[idx_third] + 0.01

idx_features = (-importance).argsort()[:2]
name_features = np.array(feature_names)[idx_features]
print('Selected features: {}'.format(name_features))

sfm = SelectFromModel(clf, threshold=threshold)
sfm.fit(X, y)
X_transform = sfm.transform(X)

n_features = sfm.transform(X).shape[1]

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']
[  6.49684455 235.99640534 521.73854261 321.06689245 569.4426838
 302.45627915   0.         143.6995665  669.92633112  66.83430445]
Selected features: ['s5' 's1']

In [58]:
importance = np.abs(svm.coef_)

idx_third = importance.argsort()[-3]
threshold = importance[idx_third] + 0.01

sfm = SelectFromModel(svm, threshold=threshold)
sfm.fit(x_train, y_train)
X_transform = sfm.transform(x_train)

n_features = sfm.transform(X).shape[1]

ValueError: WRITEBACKIFCOPY base is read-only